[tool.poetry]
name = "utils"
version = "0.1.0"
description = ""
authors = ["NikoJT <niko.tarmaa@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pypdf2 = "^3.0.0"
pyttsx3 = "^2.90"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
